In [1]:
import numpy as np
from numpy import allclose as eq, conj, array

V2 = np.sqrt(2)

# Basis

In [29]:
basis_0 = array([[1, 0]], dtype=complex).T / V2
basis_1 = array([[0, 1]], dtype=complex).T / V2

In [32]:
plus = (basis_0 + basis_1) / V2
minus = (basis_0 - basis_1) / V2

In [33]:
R = (basis_0 + 1j * basis_1) / V2
L = (basis_0 - 1j * basis_1) / V2

In [34]:
assert eq(conj(basis_0).T @ basis_1, 0)
assert eq(conj(plus).T @ minus, 0)
assert eq(conj(R).T @ L, 0)

# Hadamard Gate

In [35]:
H = array([[1, 1],
           [1, -1]], dtype=complex) / V2

In [36]:
assert eq(conj(H) @ H, np.eye(2))
assert eq(H @ basis_0, plus)
assert eq(H @ plus, basis_0)

# Pauli Matrices

In [37]:
pauli_X = array([[0, 1],
                 [1, 0]], dtype=complex)

pauli_Y = array([[0, -1j],
                 [1j, 0]], dtype=complex)

pauli_Z = array([[1, 0],
                 [0, -1]], dtype=complex)

# Measurements

In [38]:
np.linalg.eig(pauli_Z)[0]

array([ 1.+0.j, -1.+0.j])

In [39]:
np.linalg.eig(pauli_Z)

(array([ 1.+0.j, -1.+0.j]),
 array([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]))